from app import db
from app.mod_sms.models import *

# ug1 = UserGroup(phone='+17868378095', active=True).show()
ug1 = UserGroup(name='Canyon Time', phone='+17868378095', active=True)
ug2 = UserGroup(name='test', phone='+18503783607', active=True)

ryan = User(fname='Ryan', lname='Kuhl', phone='+13058985985', active=True)
simon = User(fname='Simon', lname='', phone='+13109264989', active=True)
dan = User(fname='Dan', lname='Malik', phone='+14152718694', active=True)
tom = User(fname='Tom', lname='Scorer', phone='+13109022760', active=True)
steve = User(fname='Steve', lname='Makuch', phone='+16164609893', active=True)
chris = User(fname='Chris', lname='Namur', phone='+16265251486', active=True)
ben = User(fname='Ben', lname='Eisenbise', phone='+13234017625', active=True)
alex = User(fname='Alex', lname='Thorpe', phone='+14243869550', active=True)
jwahl = User(active=True, fname='John', lname='Wahl', phone='+13109852208')
ewahl = User(active=True, fname='Eric', lname='Wahl', phone='+12067998337')
david = User(active=True, fname='David', lname='Gamez', phone='+18186324490')
jason = User(active=True, fname='Jason', lname='pitsch', phone='+12624097133')
kris = User(active=True, fname='Kris', lname='Neuharth', phone='+17344743631')
khaled = User(active=True, fname='Khaled', lname='Mounir', phone='+19175417944')
josef = User(active=True, fname='Josef', lname='Busch', phone='+18583377251')
lon = User(active=True, fname='Lon', lname='Bender', phone='+13238545803')

ug1.groups_to_users.append(ryan)
ug1.groups_to_users.append(simon)
ug1.groups_to_users.append(dan)
ug1.groups_to_users.append(tom)
ug1.groups_to_users.append(steve)
ug1.groups_to_users.append(chris)
ug1.groups_to_users.append(ben)
ug1.groups_to_users.append(alex)
ug1.groups_to_users.append(jwahl)
ug1.groups_to_users.append(ewahl)
ug1.groups_to_users.append(david)
ug1.groups_to_users.append(jason)
ug1.groups_to_users.append(kris)
ug1.groups_to_users.append(khaled)
ug1.groups_to_users.append(josef)
ug1.groups_to_users.append(lon)

ug2.groups_to_users.append(ryan)

db.session.add(ug1)
db.session.add(ug2)
db.session.add(ryan)
db.session.add(simon)
db.session.add(dan)
db.session.add(tom)
db.session.add(steve)
db.session.add(chris)
db.session.add(ben)
db.session.add(alex)
db.session.add(jwahl)
db.session.add(ewahl)
db.session.add(david)
db.session.add(jason)
db.session.add(kris)
db.session.add(khaled)
db.session.add(josef)
db.session.add(lon)

db.session.commit()
